language: php

php:
  - '7.4'
  
before_script:
  - composer self-update
  - composer install --no-interaction
  
script:
  - vendor/bin/phpunit --coverage-text

notifications:
  email:
    recipients:
      - sunpreet.singh@student.vinci.be
    on_success: never
    on_failure: always
